#!/bin/bash

find . -name '*.out' -type f -print -delete
find . -name '*.lis' -type f -print -delete
find . -name '*.ic*' -type f -print -delete
find . -name '*.st*' -type f -print -delete
find . -name '*.tr*' -type f -print -delete
find . -name '*.sw*' -type f -print -delete
find . -name '*.ac*' -type f -print -delete
find . -name '*.pa*' -type f -print -delete
find . -name '*.log' -type f -print -delete
find . -name '*.bak' -type f -print -delete

